[build]
  command = "python -m pip install -r requirements.txt && netlify deploy"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
